---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# spatialBACI

<!-- badges: start -->
<!-- badges: end -->

The `spatialBACI` package for *R* aims to simplify the counterfactual impact evaluation of ecosystem conservation/restoration actions, using geospatial datasets in raster and vector format.

The main possibilities of the package include:

- Identification of candidate control and impact units of analysis
- Control-impact matching and matching evaluation
- Impact evaluation using a Before-After-Control-Impact framework

## Package installation

The latest version of the `spatialBACI` package can be installed from [GitHub](https://github.com/Space4Restoration/spatialBACI) using the [`devtools`](https://cran.r-project.org/package=devtools) package: 

``` r
library(devtools)
install_github("Space4Restoration/spatialBACI", dependencies=TRUE)
```

## Usage

See the [BACI evaluation Baviaankloof](https://space4restoration.github.io/spatialBACI/articles/BACI_Baviaanskloof.html) article for an example of use of the `spatialBACI` package with raster units of analysis, and the [Wildlife circles Finland](https://space4restoration.github.io/spatialBACI/articles/wildlife_circles_Finland.html) article for an example of vector units of analysis.

## Contribute

Visit the [Issues](https://github.com/Space4Restoration/spatialBACI/issues) page to report issues, request features, or suggest improvements.

## Acknowledgements

The package was initiated as part of the [Space4Restoration](https://itc.nl/space4restoration) project of [ITC](https://ITC.nl). Further development was supported through the OpenCoRe project funded through the Open Science Fund (OSF23.2.091 ) of the [Dutch Research Council](https://www.nwo.nl/en).

## Contact

[Jasper Van doninck](mailto:j.vandoninck@utwente.nl)  
Faculty of Geo-Information Science and Earth Observation (ITC), University of Twente  
P.O. Box 217, 7500 AE Enschede, The Netherlands  
Office: Langezijds  1116  
Tel.: +31534894768  

